#!/usr/bin/env bash
# On-instance setup — runs on the Vast.ai GPU instance.
# No external API keys required. Fully self-contained with Ollama.
#
# Usage (run ON the Vast.ai instance):
#   bash /root/vast-setup.sh
#
# Optional overrides:
#   OLLAMA_MODEL=llama3.2:3b   — smaller/faster model (default: llama3.1:8b)
#   SKIP_MODELS=1              — skip all model downloads
#   SKIP_FISH_MODELS=1         — skip fish-speech models only
#   SKIP_SDXL=1                — skip SDXL checkpoint only
#   POSTGRES_PASSWORD=xxx      — custom DB password (default: random)
#   CREATOR_PRIVATE_KEY=0x...  — Ethereum key for on-chain features (optional)

set -euo pipefail

REPO_URL="https://github.com/ma-za-kpe/god.git"
REPO_DIR="/workspace/god"
OLLAMA_MODEL="${OLLAMA_MODEL:-llama3.1:8b}"
SKIP_MODELS="${SKIP_MODELS:-0}"
SKIP_FISH_MODELS="${SKIP_FISH_MODELS:-0}"
SKIP_SDXL="${SKIP_SDXL:-0}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(openssl rand -hex 16)}"
CREATOR_PRIVATE_KEY="${CREATOR_PRIVATE_KEY:-}"

log() { echo "[vast-setup] $*"; }

# ── 1. System deps ────────────────────────────────────────────────────────────
log "Installing system dependencies..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq curl git openssl ca-certificates python3-pip

# ── 2. Docker CE ─────────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
  log "Installing Docker CE..."
  curl -fsSL https://get.docker.com | sh
fi

if ! docker compose version &>/dev/null 2>&1; then
  log "Installing docker compose plugin..."
  apt-get install -y -qq docker-compose-plugin
fi

# Vast.ai runs as a container (no systemd). Start dockerd directly.
# --iptables=false: the host kernel doesn't grant nf_tables caps to nested containers.
# Containers communicate via host-network mode; that is handled in the compose files.
if ! docker info &>/dev/null 2>&1; then
  log "Starting Docker daemon (no systemd — using dockerd directly)..."
  mkdir -p /var/log
  nohup dockerd --iptables=false > /var/log/dockerd.log 2>&1 &
  DOCKERD_PID=$!
  log "dockerd started (PID=${DOCKERD_PID}), waiting for socket..."
  for i in $(seq 1 30); do
    docker info &>/dev/null 2>&1 && break
    sleep 2
  done
  if ! docker info &>/dev/null 2>&1; then
    log "ERROR: Docker daemon failed to start. See /var/log/dockerd.log"
    cat /var/log/dockerd.log
    exit 1
  fi
fi
log "Docker daemon ready"

# On Vast.ai the NVIDIA Container Toolkit is pre-installed by the host.
# Verify GPU is visible to Docker:
if ! docker run --rm --gpus all nvidia/cuda:12.4.1-base-ubuntu22.04 nvidia-smi -L 2>/dev/null; then
  log "WARNING: GPU not visible to Docker. Check NVIDIA Container Toolkit."
fi

log "Docker: $(docker --version)"
log "Compose: $(docker compose version)"

# ── 3. Clone / update repo ────────────────────────────────────────────────────
if [ -d "$REPO_DIR/.git" ]; then
  log "Repo exists — pulling latest..."
  git -C "$REPO_DIR" pull
else
  log "Cloning ${REPO_URL}..."
  mkdir -p /workspace
  git clone "$REPO_URL" "$REPO_DIR"
fi
cd "$REPO_DIR"

# ── 4. Create .env.local ──────────────────────────────────────────────────────
log "Writing .env.local..."
cat > .env.local <<EOF
# Generated by vast-setup.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
CREATOR_PRIVATE_KEY=${CREATOR_PRIVATE_KEY}

# LLM — Ollama running in the ollama container (GPU)
LLM_PROVIDER=ollama
LLM_MODEL=${OLLAMA_MODEL}

# Avatar genesis — SDXL (no Flux, no custom nodes required)
COMFYUI_PORTRAIT_TEMPLATE=sdxl_portrait.json
COMFYUI_EXPRESSION_TEMPLATE=sdxl_expression.json
AVATAR_GENESIS_ENABLED=true
AVATAR_ENABLED=true

# Voice — fish-speech on CUDA
VOICE_ENABLED=true
VOICE_HEALTH_URL=http://fish-speech:7860

# ComfyUI
AVATAR_HEALTH_URL=http://comfyui:8188
EOF

log ".env.local written"

# ── 5. Build fish-speech image (no-warmup patch) ─────────────────────────────
log "Building patched fish-speech image..."
docker build -t fish-patch ./fish-speech

# ── 6. Download fish-speech 1.5 models (~10.4 GB) ───────────────────────────
if [ "$SKIP_MODELS" = "0" ] && [ "$SKIP_FISH_MODELS" = "0" ]; then
  log "Downloading fish-speech 1.5 models into Docker volume (~10.4 GB, takes ~5 min)..."
  docker run --rm \
    -v god_fish_speech_checkpoints:/checkpoints \
    python:3.11-slim \
    bash -c "
      pip install -q huggingface_hub &&
      python3 -c \"
from huggingface_hub import snapshot_download
snapshot_download(
    repo_id='fishaudio/fish-speech-1.5',
    local_dir='/checkpoints',
    ignore_patterns=['*.gguf','*.onnx','*.txt','*.md','README*'],
)
print('Done')
\"
    "
  log "fish-speech models ready"
else
  log "Skipping fish-speech models (SKIP_FISH_MODELS=${SKIP_FISH_MODELS})"
fi

# ── 7. Download SDXL 1.0 checkpoint for ComfyUI (~6.5 GB) ───────────────────
if [ "$SKIP_MODELS" = "0" ] && [ "$SKIP_SDXL" = "0" ]; then
  log "Downloading SDXL base 1.0 checkpoint (~6.5 GB, takes ~3 min)..."
  docker run --rm \
    -v god_comfyui_models:/models \
    python:3.11-slim \
    bash -c "
      pip install -q huggingface_hub &&
      mkdir -p /models/checkpoints &&
      python3 -c \"
from huggingface_hub import hf_hub_download
hf_hub_download(
    repo_id='stabilityai/stable-diffusion-xl-base-1.0',
    filename='sd_xl_base_1.0.safetensors',
    local_dir='/models/checkpoints',
)
print('Done')
\"
    "
  log "SDXL checkpoint ready"
else
  log "Skipping SDXL (SKIP_SDXL=${SKIP_SDXL})"
fi

# ── 8. Start the full stack ───────────────────────────────────────────────────
log "Starting GOD stack..."
docker compose \
  -f docker-compose.yml \
  -f docker-compose.vast.yml \
  --profile fish-speech \
  up -d

# ── 9. Pull Ollama model ──────────────────────────────────────────────────────
log "Waiting for Ollama to be ready..."
for i in $(seq 1 30); do
  if docker exec god-ollama ollama list &>/dev/null 2>&1; then
    break
  fi
  echo "  [${i}/30] waiting for Ollama..."
  sleep 5
done

log "Pulling ${OLLAMA_MODEL} (~4.7 GB, this is the last step)..."
docker exec god-ollama ollama pull "$OLLAMA_MODEL"
log "Ollama model ready"

# ── Done ─────────────────────────────────────────────────────────────────────
PUBLIC_IP=$(curl -sf --max-time 5 ifconfig.me 2>/dev/null || echo "<instance-ip>")

log ""
log "=================================================="
log " GOD stack is live — no API keys required"
log ""
log "   Runtime   http://${PUBLIC_IP}:8888"
log "   ComfyUI   http://${PUBLIC_IP}:8188"
log "   Ollama    http://${PUBLIC_IP}:11434"
log "   Fish TTS  http://${PUBLIC_IP}:8090"
log ""
log " Wait ~2 min for ComfyUI to finish loading, then:"
log "   curl -s -X POST http://localhost:8888/creator/genesis \\"
log "     -H 'Content-Type: application/json' \\"
log "     -d '{\"confirm\": true}' | python3 -m json.tool"
log "=================================================="
