#!/usr/bin/env bash
# Native GOD stack setup for Vast.ai — no Docker required.
# Runs all services directly on the host (Python, PostgreSQL, Redis, NATS, Ollama).
#
# Usage (run ON the Vast.ai instance):
#   bash /root/vast-setup-native.sh
#
# Overrides:
#   OLLAMA_MODEL=llama3.2:3b   — smaller model (default: llama3.1:8b)
#   SKIP_FISH=1                — skip fish-speech install
#   SKIP_COMFYUI=1             — skip ComfyUI install
#   POSTGRES_PASSWORD=xxx      — custom DB password (default: random)
#   REPO_BRANCH=main           — branch to deploy (default: feat/twitch-ne-mo-showrunner)

set -euo pipefail

REPO_URL="https://github.com/ma-za-kpe/god.git"
REPO_DIR="/workspace/god"
REPO_BRANCH="${REPO_BRANCH:-feat/twitch-ne-mo-showrunner}"
OLLAMA_MODEL="${OLLAMA_MODEL:-llama3.1:8b}"
SKIP_FISH="${SKIP_FISH:-0}"
SKIP_COMFYUI="${SKIP_COMFYUI:-0}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(openssl rand -hex 16)}"
LOG_DIR="/var/log/god"

log() { echo "[vast-native] $*"; }
mkdir -p "$LOG_DIR"

export DEBIAN_FRONTEND=noninteractive

# ── 1. System packages ────────────────────────────────────────────────────────
log "Installing system packages..."
apt-get update -qq
apt-get install -y -qq \
  curl git openssl ca-certificates \
  postgresql postgresql-client \
  redis-server \
  python3-pip python3-venv python3-dev \
  build-essential libssl-dev libffi-dev \
  ffmpeg libsndfile1 \
  portaudio19-dev \
  nodejs npm

# ── 2. NATS server ────────────────────────────────────────────────────────────
if ! command -v nats-server &>/dev/null; then
  log "Installing NATS server..."
  NATS_VER="v2.10.22"
  curl -sL "https://github.com/nats-io/nats-server/releases/download/${NATS_VER}/nats-server-${NATS_VER}-linux-amd64.tar.gz" \
    | tar -xz -C /usr/local/bin --strip-components=1 "nats-server-${NATS_VER}-linux-amd64/nats-server"
fi
log "NATS: $(nats-server --version)"

# ── 3. Ollama (GPU-accelerated LLM) ──────────────────────────────────────────
if ! command -v ollama &>/dev/null; then
  log "Installing Ollama..."
  curl -fsSL https://ollama.com/install.sh | sh
fi
log "Ollama: $(ollama --version 2>/dev/null | head -1)"

# ── 4. Clone / update repo ────────────────────────────────────────────────────
if [ -d "$REPO_DIR/.git" ]; then
  log "Repo exists — syncing branch ${REPO_BRANCH}..."
  GIT_TERMINAL_PROMPT=0 git -C "$REPO_DIR" fetch origin || true
  git -C "$REPO_DIR" checkout "$REPO_BRANCH" 2>/dev/null || true
  GIT_TERMINAL_PROMPT=0 git -C "$REPO_DIR" pull || log "WARNING: git pull failed"
else
  log "Cloning ${REPO_URL} (branch: ${REPO_BRANCH})..."
  mkdir -p /workspace
  GIT_TERMINAL_PROMPT=0 git clone --branch "$REPO_BRANCH" --single-branch "$REPO_URL" "$REPO_DIR"
fi
cd "$REPO_DIR"

# ── 5. PostgreSQL ─────────────────────────────────────────────────────────────
log "Configuring PostgreSQL..."
service postgresql start || pg_ctlcluster 14 main start || true
sleep 3
# Create user and database if they don't exist
sudo -u postgres psql -c "CREATE USER god WITH PASSWORD '${POSTGRES_PASSWORD}';" 2>/dev/null || true
sudo -u postgres psql -c "CREATE DATABASE god OWNER god;" 2>/dev/null || true
sudo -u postgres psql -c "ALTER USER god WITH PASSWORD '${POSTGRES_PASSWORD}';" 2>/dev/null || true
log "PostgreSQL ready"

# ── 6. Redis ──────────────────────────────────────────────────────────────────
log "Starting Redis..."
service redis-server start || redis-server --daemonize yes || true
sleep 2
redis-cli ping &>/dev/null && log "Redis ready" || log "WARNING: Redis not responding"

# ── 7. NATS ───────────────────────────────────────────────────────────────────
log "Starting NATS..."
if ! pgrep -x nats-server &>/dev/null; then
  nohup nats-server -p 4222 > "$LOG_DIR/nats.log" 2>&1 &
  sleep 2
fi
log "NATS ready"

# ── 8. Runtime Python environment ─────────────────────────────────────────────
log "Installing runtime Python dependencies..."
cd "$REPO_DIR/runtime"
python3 -m venv /opt/god-venv
source /opt/god-venv/bin/activate

# Install pip packages from runtime
pip install --quiet --upgrade pip
pip install --quiet -r requirements.txt 2>/dev/null || \
  pip install --quiet \
    fastapi uvicorn httpx asyncpg psycopg2-binary redis nats-py \
    aiofiles python-multipart ipfshttpclient \
    web3 eth-account 2>/dev/null || true

cd "$REPO_DIR"

# ── 9. .env.local ─────────────────────────────────────────────────────────────
log "Writing .env.local..."
cat > .env.local <<EOF
# Generated by vast-setup-native.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://god:${POSTGRES_PASSWORD}@localhost:5432/god

# LLM — Ollama on localhost
LLM_PROVIDER=ollama
LLM_MODEL=${OLLAMA_MODEL}
OLLAMA_BASE_URL=http://localhost:11434

# All services on localhost (native, no Docker)
NATS_URL=nats://localhost:4222
REDIS_URL=redis://localhost:6379
IPFS_API=http://localhost:5001

# Avatar genesis — SDXL
COMFYUI_PORTRAIT_TEMPLATE=sdxl_portrait.json
COMFYUI_EXPRESSION_TEMPLATE=sdxl_expression.json
AVATAR_GENESIS_ENABLED=true
AVATAR_ENABLED=true
COMFYUI_ENDPOINT=http://localhost:8188
AVATAR_HEALTH_URL=http://localhost:8188

# Voice — fish-speech
VOICE_ENABLED=true
TTS_ENDPOINT=http://localhost:7860
VOICE_HEALTH_URL=http://localhost:7860
EOF
log ".env.local written"

# ── 10. Ollama daemon + model ─────────────────────────────────────────────────
log "Starting Ollama daemon..."
if ! pgrep -x ollama &>/dev/null; then
  # OLLAMA_KEEP_ALIVE=0 unloads the model from VRAM after each request,
  # freeing GPU memory for ComfyUI and fish-speech between LLM calls.
  OLLAMA_KEEP_ALIVE=0 nohup ollama serve > "$LOG_DIR/ollama.log" 2>&1 &
fi
log "Waiting for Ollama..."
for i in $(seq 1 30); do
  curl -sf http://localhost:11434/api/tags &>/dev/null && break
  sleep 3
done
log "Pulling ${OLLAMA_MODEL}..."
ollama pull "$OLLAMA_MODEL"
log "Ollama ready"

# ── 11. ComfyUI (optional) ────────────────────────────────────────────────────
if [ "$SKIP_COMFYUI" = "0" ]; then
  log "Installing ComfyUI..."
  if [ ! -d /opt/ComfyUI ]; then
    git clone --depth 1 https://github.com/comfyanonymous/ComfyUI /opt/ComfyUI
  fi
  cd /opt/ComfyUI
  source /opt/god-venv/bin/activate
  pip install --quiet -r requirements.txt

  # Download SDXL checkpoint
  log "Downloading SDXL base 1.0 (~6.5 GB)..."
  mkdir -p models/checkpoints
  python3 -c "
from huggingface_hub import hf_hub_download
hf_hub_download(
    repo_id='stabilityai/stable-diffusion-xl-base-1.0',
    filename='sd_xl_base_1.0.safetensors',
    local_dir='models/checkpoints',
)
print('SDXL ready')
" || log "WARNING: SDXL download failed — avatar generation will be skipped"

  # Start ComfyUI in background
  log "Starting ComfyUI on :8188..."
  # Unset empty CUDA_VISIBLE_DEVICES — empty string hides GPUs from CUDA
  [ -z "${CUDA_VISIBLE_DEVICES:-}" ] && unset CUDA_VISIBLE_DEVICES
  nohup python3 main.py --listen 0.0.0.0 --port 8188 --disable-auto-launch \
    > "$LOG_DIR/comfyui.log" 2>&1 &
  cd "$REPO_DIR"
fi

# ── 12. fish-speech (optional) ────────────────────────────────────────────────
if [ "$SKIP_FISH" = "0" ]; then
  log "Installing fish-speech..."
  # portaudio19-dev must already be installed (step 1) or pyaudio build fails
  if ! command -v uv &>/dev/null; then
    pip install --quiet uv
  fi
  if [ ! -d /opt/fish-speech ]; then
    git clone --depth 1 https://github.com/fishaudio/fish-speech /opt/fish-speech
  fi
  cd /opt/fish-speech
  # uv lands in the venv bin dir, not system PATH — discover it explicitly
  UV=$(find /opt/god-venv/bin /root/.local/bin -name uv -type f 2>/dev/null | head -1)
  UV="${UV:-$(command -v uv)}"
  "$UV" sync --no-dev --quiet

  # Download fish-speech 1.5 models
  log "Downloading fish-speech 1.5 models (~10.4 GB)..."
  pip install --quiet huggingface_hub
  python3 -c "
from huggingface_hub import snapshot_download
snapshot_download(
    repo_id='fishaudio/fish-speech-1.5',
    local_dir='checkpoints',
    ignore_patterns=['*.gguf','*.onnx','*.txt','*.md','README*'],
)
print('fish-speech models ready')
" || log "WARNING: fish-speech model download failed"

  # Start fish-speech API server
  log "Starting fish-speech on :7860..."
  # Unset CUDA_VISIBLE_DEVICES if empty — empty string hides GPUs from CUDA
  [ -z "${CUDA_VISIBLE_DEVICES:-}" ] && unset CUDA_VISIBLE_DEVICES
  nohup "$UV" run tools/api_server.py \
    --llama-checkpoint-path checkpoints \
    --decoder-checkpoint-path checkpoints/codec.pth \
    --decoder-config-name modded_dac_vq \
    --device cuda \
    --listen 0.0.0.0:7860 \
    > "$LOG_DIR/fish-speech.log" 2>&1 &
  cd "$REPO_DIR"
fi

# ── 13. Database schema init + migrations ─────────────────────────────────────
log "Initialising database schema..."
PGPASSWORD="${POSTGRES_PASSWORD}" psql -U god -d god -h localhost \
  -f "$REPO_DIR/scripts/init-db.sql" 2>/dev/null || \
  log "WARNING: init-db.sql failed (schema may already exist — continuing)"

log "Running alembic migrations..."
cd "$REPO_DIR/runtime"
source /opt/god-venv/bin/activate
DATABASE_URL="postgresql://god:${POSTGRES_PASSWORD}@localhost:5432/god" \
  python3 -m alembic upgrade head 2>/dev/null || \
  log "WARNING: alembic migrations failed (DB may not be ready yet)"

# ── 14. Start the runtime ─────────────────────────────────────────────────────
log "Starting GOD runtime on :8888..."
cd "$REPO_DIR/runtime"
source /opt/god-venv/bin/activate
# Load .env.local variables
set -a; source "$REPO_DIR/.env.local"; set +a
nohup python3 -m uvicorn src.main:app --host 0.0.0.0 --port 8888 \
  > "$LOG_DIR/runtime.log" 2>&1 &

# ── Done ──────────────────────────────────────────────────────────────────────
PUBLIC_IP=$(curl -sf --max-time 5 ifconfig.me 2>/dev/null || echo "<instance-ip>")
sleep 5

log ""
log "=================================================="
log " GOD stack is live (native, no Docker)"
log ""
log "   Runtime   http://${PUBLIC_IP}:8888"
log "   ComfyUI   http://${PUBLIC_IP}:8188"
log "   Ollama    http://${PUBLIC_IP}:11434"
log "   Fish TTS  http://${PUBLIC_IP}:7860"
log ""
log " Logs in: ${LOG_DIR}/"
log ""
log " Genesis:"
log "   curl -s -X POST http://localhost:8888/creator/genesis \\"
log "     -H 'Content-Type: application/json' \\"
log "     -d '{\"confirm\": true}' | python3 -m json.tool"
log "=================================================="

# Quick health check
curl -sf http://localhost:8888/health 2>/dev/null && log "Runtime health: OK" || log "Runtime: still starting..."
curl -sf http://localhost:11434/api/tags 2>/dev/null && log "Ollama health: OK" || log "Ollama: not responding"
